# Turn on validation, so we can use import:
version: ~> 1.0

# TODO
# export sandbox token to run tests
# current travis file will cause all tests to fail

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

script:
- APPMAP=true bundle exec rake

after_script:
- env DEBUG=true ruby ./upload-appmaps tmp/appmap/minitest/*
